settings:
  name: Kubernetes clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"  
sidebar:
  entries:
    - title: Kubernetes clusters docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Kubernetes data management
          url: /concept-kubernetes.html
        - title: Quick start
          url: /task/task-k8s-quick-start.html
    - title: Requirements
      entries:
        - title: Kubernetes clusters on AWS
          url: /requirements/kubernetes-reqs-aws.html
        - title: Kubernetes clusters on Azure
          url: /requirements/kubernetes-reqs-aks.html
        - title: Kubernetes clusters on Google Cloud
          url: /requirements/kubernetes-reqs-gke.html
        - title: Kubernetes clusters on OpenShift
          url: /requirements/kubernetes-reqs-openshift.html
    - title: Add Kubernetes clusters
      entries:
        - title: Add clusters on AWS
          url: /task/task-kubernetes-discover-aws.html
        - title: Add clusters on Azure
          url: /task/task-kubernetes-discover-azure.html
        - title: Add clusters on Google Cloud
          url: /task/task-kubernetes-discover-gke.html
        - title: Import OpenShift clusters
          url: /task/task-kubernetes-discover-openshift.html
    - title: Manage Kubernetes clusters
      entries:
        - title: Manage Astra Trident
          url: /task/task-k8s-manage-trident.html
        - title: Manage storage classes
          url: /task/task-k8s-manage-storage-classes.html
        - title: View persistent volumes
          url: /task/task-k8s-manage-persistent-volumes.html
        - title: Remove clusters
          url: /task/task-k8s-manage-remove-cluster.html
        - title: Enable NetApp cloud data services
          url: /task/task-kubernetes-enable-services.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
    name: BlueXP
    repo: bluexp-family
    sidebar_label: All BlueXP documentation