settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Kubernetes docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Kubernetes data management
          url: /concept-kubernetes.html
        - title: Requirements
          entries:
            - title: Kubernetes clusters on AWS
              url: /kubernetes-reqs-aws.html
            - title: Kubernetes clusters on Azure
              url: /kubernetes-reqs-aks.html
            - title: Kubernetes clusters on Google Cloud
              url: /kubernetes-reqs-gke.html
        - title: Add Kubernetes clusters
          entries:
            - title: Add clusters on AWS
              url: /task-kubernetes-discover-aws.html
            - title: Add clusters on Azure
              url: /task-kubernetes-discover-azure.html
            - title: Add clusters on Google Cloud
              url: /task-kubernetes-discover-gke.html
    - title: Enable data services on Kubernetes clusters
      url: task-kubernetes-enable-services.html
    - title: Knowledge and support
      url: /get-help.html
    - title: Legal notices
      url: /legal-notices.html
