settings:
  name: Kubernetes clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  filter:
    label: Cloud provider
    default: All cloud providers
    options:
      - name: Amazon Web Services
        alias: AWS
        id: aws
      - name: Google Cloud
        alias: Google Cloud
        id: gcp
      - name: Microsoft Azure
        alias: Azure
        id: azure
sidebar:
  entries:
    - title: Kubernetes clusters docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Kubernetes data management
          url: /concept-kubernetes.html
        - title: Quick start
          url: /task/task-k8s-quick-start.html
    - title: Requirements
      entries:
        - title: Kubernetes clusters on AWS
          flavor: aws
          url: /requirements/kubernetes-reqs-aws.html
        - title: Kubernetes clusters on Azure
          flavor: azure
          url: /requirements/kubernetes-reqs-aks.html
        - title: Kubernetes clusters on Google Cloud
          flavor: gcp
          url: /requirements/kubernetes-reqs-gke.html
    - title: Add Kubernetes clusters
      entries:
        - title: Add clusters on AWS
          flavor: aws
          url: /task/task-kubernetes-discover-aws.html
        - title: Add clusters on Azure
          flavor: azure
          url: /task/task-kubernetes-discover-azure.html
        - title: Add clusters on Google Cloud
          flavor: gcp
          url: /task/task-kubernetes-discover-gke.html
    - title: Manage Kubernetes clusters
      url: /concept-manage-k8s.html
      entries:
        - title: Install Astra Trident
          url: /task/task-k8s-manage-trident.html
        - title: Manage storage classes
          url: /task/task-k8s-manage-storage-classes.html
        - title: View persistent volumes
          url: /task/task-k8s-manage-persistent-volumes.html
        - title: Remove clusters
          url: /task/task-k8s-manage-remove-cluster.html
        - title: Enable NetApp cloud data services
          url: /task/task-kubernetes-enable-services.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
    name: Cloud Manager
    repo: cloud-manager-family
    sidebar_label: All Cloud Manager documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: /whats-new.html
        - title: Learn about Kubernetes data management
          url: /concept-kubernetes.html
        - title: Quick start
          url: /task/task-k8s-quick-start.html
    - title: Requirements
      links:
        - title: Kubernetes clusters on AWS
          flavor: aws
          url: /requirements/kubernetes-reqs-aws.html
        - title: Kubernetes clusters on Azure
          flavor: azure
          url: /requirements/kubernetes-reqs-aks.html
        - title: Kubernetes clusters on Google Cloud
          flavor: gcp
          url: /requirements/kubernetes-reqs-gke.html
    - title: Add Kubernetes clusters
      links:
        - title: Add clusters on AWS
          flavor: aws
          url: /task/task-kubernetes-discover-aws.html
        - title: Add clusters on Azure
          flavor: azure
          url: /task/task-kubernetes-discover-azure.html
        - title: Add clusters on Google Cloud
          flavor: gcp
          url: /task/task-kubernetes-discover-gke.html
    - title: Manage Kubernetes clusters
      links:
       - title: Install Astra Trident
         url: /task/task-k8s-manage-trident.html
       - title: Manage storage classes
         url: /task/task-k8s-manage-storage-classes.html
       - title: View persistent volumes
         url: /task/task-k8s-manage-persistent-volumes.html
       - title: Remove clusters
         url: /task/task-k8s-manage-remove-cluster.html
       - title: Enable data services
         url: /task/task-kubernetes-enable-services.html
    - title: Get help with Cloud Manager
      links:
        - title: Register for support
          url: /support/task-support-registration.html
        - title: Get help
          url: /support/task-get-help.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
